name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install --force
        ./deploy.sh
  release-project:
    name: Release project
    runs-on: ubuntu-lastest
    needs: build
    steps:
    - name: deploy release
      uses: ncipollo/release-action@v1
      with:
          artifacts: "dist_resume/installers/*.deb"
          bodyFile: "body.md"
          tag: ${{ github.run_number }}
          name: Release ${{ github.run_number }}
