name: NodeJS with resume-maloi

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install --force
        ./deploy.sh
        tree $(Build.SourcesDirectory)



    - name: installer ubuntu
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: dist_resume/installers/*.deb
        retention-days: 5
  release-project:
    name: Release project
    runs-on: ubuntu-latest
    needs:  [build-node]
    steps:

    - name: "Local three"
      run: |
        tree $(Build.SourcesDirectory)

    - name: deploy release
      uses: ncipollo/release-action@v1
      with:
          artifacts: "installer ubuntu"
          body: "make executable resume-maloi"
          tag: ${{ github.run_number }}
          name: Release ${{ github.run_number }}
